name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        # TensorRT 10.11.0.33
        # CUDA 12.9.1
        container: nvcr.io/nvidia/tensorrt:25.06-py3

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: "true"

            - name: Make
              run: make
              env:
                  CPLUS_INCLUDE_PATH: "/usr/local/cuda/include"

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: libnvinfer_lean_c
                  path: libnvinfer_lean_c.so.10.11.0
                  retention-days: 90
                  if-no-files-found: error
